// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHdQPuo8WFR1AFCdgSpOXZFCSvPrce318',
    appId: '1:144068718121:web:ec4dacdc14969072eef638',
    messagingSenderId: '144068718121',
    projectId: 'blood-donation-4da9b',
    authDomain: 'blood-donation-4da9b.firebaseapp.com',
    storageBucket: 'blood-donation-4da9b.appspot.com',
    measurementId: 'G-PC66EN5E5J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCNP6NtXeGMvTJYo02O4a3kyMWy7sPgD8',
    appId: '1:144068718121:android:078d0e15caf7bd23eef638',
    messagingSenderId: '144068718121',
    projectId: 'blood-donation-4da9b',
    storageBucket: 'blood-donation-4da9b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWcbV8bxgnHiuzWNX_ommJgodKWSze4iQ',
    appId: '1:144068718121:ios:4e94d27717932278eef638',
    messagingSenderId: '144068718121',
    projectId: 'blood-donation-4da9b',
    storageBucket: 'blood-donation-4da9b.appspot.com',
    iosClientId: '144068718121-5i78edek6bb28a2ul8qjrn9p0upgb73r.apps.googleusercontent.com',
    iosBundleId: 'com.example.bloodDonation',
  );
}
